[package]
name = "spl-token-mint"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.0.14"
spl-token = { version="6.0.0", features = [ "no-entrypoint" ] }

[lib]
crate-type = ["cdylib"]
